groups:
- name: targets.rules
  rules:
  - alert: VLLMTargetDown
    expr: up{job="vllm"} == 0
    for: 2m
    labels: {severity: critical}
    annotations:
      summary: "vLLM metrics target is down"

  - alert: OpenWebUIOTELTargetDown
    expr: up{job="openwebui-otel"} == 0
    for: 2m
    labels: {severity: critical}
    annotations:
      summary: "Open WebUI OTEL metrics target is down"

- name: vllm.rules
  rules:
  - alert: VLLMErrorRateHigh
    expr: sum(rate(vllm_requests_exceptions_total[5m])) > 0.05
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "vLLM exception rate elevated"
