services:
  vllm-chat:
    image: vllm/vllm-openai:v0.10.2
    mem_limit: 8g
    cpus: 4
    ports:
      - "8000:8000"
    shm_size: "3g"
    privileged: true
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    command: >
      --model=Qwen/Qwen2.5-VL-3B-Instruct-AWQ
      --max-model-len=16K
      --gpu-memory-utilization=0.75
      --tensor-parallel-size=1
      --swap-space=0
  docling:
    image: ghcr.io/docling-project/docling-serve-cu128:v1.5.1
    mem_limit: 8g
    cpus: 2
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - ./docling.env
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.30
    mem_limit: 2g
    cpus: 2
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./owui.env
