services:
  vllm-chat:
    build:
      context: ./vllm
      dockerfile: docker/Dockerfile.cpu
      target: vllm-openai
      args:
        VLLM_CPU_AVX512BF16: "false"  # or "true"
        VLLM_CPU_AVX512VNNI: "false"  # or "true"
    mem_limit: 4g
    shm_size: "2g"
    cpus: 2
    privileged: true
    environment:
      VLLM_CPU_KVCACHE_SPACE: "1"
      VLLM_CPU_OMP_THREADS_BIND: "0-1"
    ports:
      - "8000:8000"
    command: >
      --model=HuggingFaceTB/SmolVLM-256M-Instruct
      --max-model-len=4K
      --tensor-parallel-size=1
  docling:
    image: ghcr.io/docling-project/docling-serve-cpu:v1.7.0
    ports:
      - "5001:5001"
    env_file:
      - ./docling.env
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.34-slim
    ports:
      - "8080:8080"
    env_file:
      - ./owui.env
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - "9090:9090"
    depends_on:
      - vllm-chat
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
