services:
  vllm-chat:
    build:
      context: /Users/tim/Projekte/da-ai-platform/platform/vllm
      dockerfile: docker/Dockerfile.cpu
      target: vllm-openai
      args:
        VLLM_CPU_AVX512BF16: "false"  # or "true"
        VLLM_CPU_AVX512VNNI: "false"  # or "true"
    mem_limit: 4g
    cpus: 2
    volumes:
      - /Users/tim/Projekte/da-ai-platform/platform/models/Qwen3-0.6B:/Qwen3-0.6B
    ports:
      - "8000:8000"
    environment:
      VLLM_CPU_KVCACHE_SPACE: "1"
      VLLM_CPU_OMP_THREADS_BIND: "0-1"
    shm_size: "3g"
    privileged: true
    command: >
      --model=/Qwen3-0.6B
      --max-model-len=2048
  vllm-embed:
    build:
      context: /Users/tim/Projekte/da-ai-platform/platform/vllm
      dockerfile: docker/Dockerfile.cpu
      target: vllm-openai
      args:
        VLLM_CPU_AVX512BF16: "false"  # or "true"
        VLLM_CPU_AVX512VNNI: "false"  # or "true"
    mem_limit: 4g
    cpus: 2
    volumes:
      - /Users/tim/Projekte/da-ai-platform/platform/models/Qwen3-Embedding-0.6B:/Qwen3-Embedding-0.6B
    ports:
      - "8001:8000"
    environment:
      VLLM_CPU_KVCACHE_SPACE: "1"
      VLLM_CPU_OMP_THREADS_BIND: "2-3"
    shm_size: "3g"
    privileged: true
    command: >
      --model=/Qwen3-Embedding-0.6B
      --dtype=bfloat16
      --max-model-len=1024
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    mem_limit: 512m
    cpus: 0.5
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./LibreChat/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./LibreChat/librechat.yaml
        target: /app/librechat.yaml
      - ./LibreChat/images:/app/client/public/images
      - ./LibreChat/uploads:/app/uploads
      - ./LibreChat/logs:/app/api/logs
  client:
    image: nginx:1.27.0-alpine
    mem_limit: 512m
    cpus: 0.5
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./LibreChat/client/nginx.conf:/etc/nginx/conf.d/default.conf
  mongodb:
    image: mongo
    mem_limit: 512m
    cpus: 0.5
    restart: always
    volumes:
      - ./LibreChat/data-node:/data/db
    command: mongod --noauth
  vectordb:
    image: ankane/pgvector:latest
    mem_limit: 512m
    cpus: 0.5
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    mem_limit: 512m
    cpus: 0.5
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - DEBUG_RAG_API=true
      - DEBUG_PGVECTOR_QUERIES=true
    ports:
      - 8003:8000
    restart: always
    depends_on:
      - vectordb
    env_file:
      - ./LibreChat/.env

volumes:
  pgdata2:
