receivers:
  otlp:
    protocols:
      grpc:    # 0.0.0.0:4317
      http:    # 0.0.0.0:4318 (optional)

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: "openwebui"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: []   # add Jaeger/Tempo later if desired
